//! Orchestration: scan → extract → run rules → score.
//!
//! The score starts at 100 and loses 15 per error finding and 5 per warning,
//! clamped at zero. Findings are normalized by the rules layer before scoring.

use crate::functions::extract_functions;
use crate::lang::Language;
use crate::mask::{scan, LineIndex};
use crate::rules::{run_rules, Finding};

/// Outcome of analyzing one source snippet.
#[derive(Debug, Clone)]
pub struct AnalysisResult {
    pub score: u32,
    pub findings: Vec<Finding>,
}

/// Analyzes `source` for `language`, returning the quality score and findings.
pub fn analyze(language: Language, source: &str) -> AnalysisResult {
    let scan = scan(language, source);
    let functions = extract_functions(language, &scan);
    let lines: Vec<String> = source.lines().map(str::to_string).collect();
    let masked_text = scan.masked_lines.join("\n");
    let index = LineIndex::new(&masked_text);

    let analysis = crate::rules::Analysis {
        language,
        lines: &lines,
        masked_text: &masked_text,
        index: &index,
        scan: &scan,
        functions: &functions,
    };
    let findings = run_rules(&analysis);

    let penalty: u32 = findings
        .iter()
        .map(|finding| finding.severity.penalty())
        .sum();
    AnalysisResult {
        score: 100u32.saturating_sub(penalty),
        findings,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn clean_code_keeps_full_score() {
        let result = analyze(
            Language::Go,
            "func Sum(items []int) int {\n\ttotal := 0\n\tfor _, item := range items {\n\t\ttotal += item\n\t}\n\treturn total\n}\n",
        );
        assert!(result.findings.is_empty());
        assert_eq!(result.score, 100);
    }

    #[test]
    fn penalties_follow_severity_weights() {
        let sloppy = "// Generated by CodeSmith\nfunction save(data) {}\n";
        let result = analyze(Language::TypeScript, sloppy);
        let errors = result
            .findings
            .iter()
            .filter(|finding| finding.severity.penalty() == 15)
            .count();
        let warnings = result
            .findings
            .iter()
            .filter(|finding| finding.severity.penalty() == 5)
            .count();
        assert!(errors >= 2);
        assert!(warnings >= 1);
        let expected = 100u32.saturating_sub(errors as u32 * 15 + warnings as u32 * 5);
        assert_eq!(result.score, expected);
    }

    #[test]
    fn score_never_goes_below_zero() {
        let awful = "// TODO a\n// TODO b\n// TODO c\n// TODO d\n// TODO e\n// TODO f\n// TODO g\nconst x = 1;\n";
        let result = analyze(Language::TypeScript, awful);
        assert_eq!(result.score, 0);
    }

    #[test]
    fn every_language_is_wired_end_to_end() {
        let stubs: [(Language, &str); 3] = [
            (Language::TypeScript, "function stub() {}\n"),
            (Language::Python, "def stub():\n    pass\n"),
            (Language::Go, "func stub() {\n}\n"),
        ];
        for (language, snippet) in stubs {
            let result = analyze(language, snippet);
            assert!(
                !result.findings.is_empty(),
                "{language} produced no findings"
            );
            assert!(result.score < 100, "{language} scored {}", result.score);
        }
    }
}
