//! # izanagi_core — the Izanagi Quality Engine
//!
//! Static structural validation of TypeScript, Python and Go sources against
//! seven slop/stub heuristics (`STUB_BODY`, `EMPTY_FUNCTION`, `GENERIC_CATCH`,
//! `GENERIC_NAME`, `REDUNDANT_COMMENT`, `AI_WATERMARK`, `LONG_FUNCTION`),
//! exposed both as a library and through the `izanagi-core` binary speaking a
//! JSON line-delimited protocol on stdin/stdout.
//!
//! Library usage:
//!
//! ```
//! use izanagi_core::{analyze, Language};
//!
//! let result = analyze(Language::Python, "def save():\n    pass\n");
//! assert!(result.score < 100);
//! assert!(result.findings.iter().any(|finding| finding.rule == "STUB_BODY"));
//! ```
//!
//! Protocol usage (one request per line, one response per line, EOF ends):
//!
//! ```text
//! $ echo '{"op":"validate","language":"go","code":"func f() {}"}' | izanagi-core
//! {"ok":true,"score":85,"findings":[{"rule":"EMPTY_FUNCTION",…}]}
//! ```
//!
//! Architecture: [`mask`] blanks comments/strings while preserving line
//! structure; [`functions`] extracts function extents from that skeleton;
//! [`rules`] evaluates the seven heuristics with exact line attribution;
//! [`engine`] scores; [`protocol`] owns the wire contract; under the `wasm`
//! feature, [`wasm`] exposes the same engine to JavaScript/WebAssembly.

pub mod engine;
pub mod functions;
pub mod lang;
pub mod mask;
pub mod protocol;
pub mod rules;
#[cfg(feature = "wasm")]
pub mod wasm;

pub use engine::{analyze, AnalysisResult};
pub use functions::{extract_functions, ExtentKind, FunctionExtent};
pub use lang::Language;
pub use mask::{scan, CommentHit, CommentKind, LineIndex, Scan, StringHit};
pub use protocol::{handle_request, run as run_protocol, PROTOCOL_VERSION};
pub use rules::{run_rules, Finding, Severity, RULE_IDS};

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn public_api_end_to_end() {
        let result = analyze(
            Language::TypeScript,
            "// Generated by GPT\n// create user\nconst user = createUser();\n",
        );
        let rules: Vec<&str> = result.findings.iter().map(|f| f.rule.as_str()).collect();
        assert!(rules.contains(&"AI_WATERMARK"));
        assert!(rules.contains(&"REDUNDANT_COMMENT"));
        assert!(result.score < 100);
    }
}
