//! The seven Quality-Engine rules evaluated over a precomputed [`Analysis`].
//!
//! Every rule consumes the masked skeleton (comments/strings blanked) plus
//! raw lines, so heuristics never trip over braces or keywords inside
//! literals. Findings carry exact 1-based line numbers and come out
//! normalized: deduplicated, ordered by line, then by canonical rule order.

use std::collections::{BTreeSet, HashSet};

use serde::Serialize;

use crate::functions::{
    find_word, indent_width, matching_brace, matching_paren, skip_ws, ExtentKind, FunctionExtent,
};
use crate::lang::Language;
use crate::mask::{CommentKind, LineIndex, Scan};

/// Stable rule identifiers exposed through the `rules` protocol operation.
pub const RULE_IDS: [&str; 7] = [
    "STUB_BODY",
    "EMPTY_FUNCTION",
    "GENERIC_CATCH",
    "GENERIC_NAME",
    "REDUNDANT_COMMENT",
    "AI_WATERMARK",
    "LONG_FUNCTION",
];

/// Decision points tolerated per function before `LONG_FUNCTION` fires.
const DECISION_LIMIT: usize = 15;

const STUB_PHRASES: [&str; 2] = ["implement later", "not implemented"];
const GENERIC_NAMES: [&str; 5] = ["data", "temp", "foo", "bar", "obj"];
const WATERMARKS: [&str; 3] = ["generated by", "as an ai", "co-authored-by: ai"];

/// How heavily a finding weighs against the final score.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize)]
#[serde(rename_all = "lowercase")]
pub enum Severity {
    Error,
    Warning,
}

impl Severity {
    pub(crate) const fn penalty(self) -> u32 {
        match self {
            Self::Error => 15,
            Self::Warning => 5,
        }
    }
}

/// One lint finding, shaped exactly as the wire contract requires.
#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
pub struct Finding {
    pub rule: String,
    pub severity: Severity,
    pub line: u32,
    pub message: String,
}

/// Precomputed context shared by every rule.
pub struct Analysis<'a> {
    pub language: Language,
    /// Raw source lines; `lines[n - 1]` is line n.
    pub lines: &'a [String],
    /// Masked lines joined with `\n`.
    pub masked_text: &'a str,
    /// Byte-index → line lookup over [`Self::masked_text`].
    pub index: &'a LineIndex,
    /// Masking output: per-line comment/string hits.
    pub scan: &'a Scan,
    /// Extracted function extents.
    pub functions: &'a [FunctionExtent],
}

impl<'a> Analysis<'a> {
    /// Masked inner text of a brace-delimited extent.
    fn braced_inner(&self, extent: &FunctionExtent) -> Option<&'a str> {
        match &extent.kind {
            ExtentKind::Braced {
                open_index,
                close_index,
            } => self.masked_text.get(open_index + 1..*close_index),
            ExtentKind::Indented => None,
        }
    }

    /// Inclusive 1-based line span of a function's body region (brace lines
    /// included for braced languages, header excluded for indented ones).
    fn body_span(&self, extent: &FunctionExtent) -> (usize, usize) {
        match &extent.kind {
            ExtentKind::Braced {
                open_index,
                close_index,
            } => {
                let first = self.index.line_of(*open_index);
                let last = self.index.line_of(close_index.saturating_sub(1));
                (first.min(last), first.max(last))
            }
            ExtentKind::Indented => (extent.header_line + 1, extent.end_line),
        }
    }

    /// Body lines owned by this extent itself: child function subtrees are
    /// carved out so nested `def`s never count towards their parent twice.
    fn owned_body_lines(&self, extent: &FunctionExtent) -> Vec<usize> {
        let (start, end) = self.body_span(extent);
        if start > end {
            return Vec::new();
        }
        let children: Vec<(usize, usize)> = self
            .functions
            .iter()
            .filter(|other| other.header_line > start && other.header_line <= end)
            .filter(|other| other.header_line != extent.header_line)
            .map(|child| (child.header_line, child.end_line))
            .collect();
        (start..=end)
            .filter(|line| !children.iter().any(|(from, to)| line >= from && line <= to))
            .collect()
    }
}

/// Runs every rule once and normalizes the combined findings.
pub fn run_rules(analysis: &Analysis<'_>) -> Vec<Finding> {
    let mut findings = Vec::new();
    findings.extend(stub_body(analysis));
    findings.extend(empty_function(analysis));
    findings.extend(generic_catch(analysis));
    findings.extend(generic_name(analysis));
    findings.extend(redundant_comment(analysis));
    findings.extend(ai_watermark(analysis));
    findings.extend(long_function(analysis));
    normalize(findings)
}

fn error_finding(rule: &str, line: usize, message: impl Into<String>) -> Finding {
    Finding {
        rule: rule.to_string(),
        severity: Severity::Error,
        line: line as u32,
        message: message.into(),
    }
}

fn warning_finding(rule: &str, line: usize, message: impl Into<String>) -> Finding {
    Finding {
        rule: rule.to_string(),
        severity: Severity::Warning,
        line: line as u32,
        message: message.into(),
    }
}

fn normalize(mut findings: Vec<Finding>) -> Vec<Finding> {
    let mut seen = HashSet::new();
    findings.retain(|finding| {
        seen.insert((finding.rule.clone(), finding.line, finding.message.clone()))
    });
    findings.sort_by(|x, y| {
        x.line
            .cmp(&y.line)
            .then_with(|| rule_rank(&x.rule).cmp(&rule_rank(&y.rule)))
            .then_with(|| x.message.cmp(&y.message))
    });
    findings
}

fn rule_rank(rule: &str) -> usize {
    RULE_IDS
        .iter()
        .position(|id| *id == rule)
        .unwrap_or(usize::MAX)
}

// ---------------------------------------------------------------- STUB_BODY

fn stub_markers_in(text: &str) -> Vec<&'static str> {
    let lowered = text.to_lowercase();
    let mut markers: Vec<&'static str> = Vec::new();
    for token in word_tokens(text) {
        let marker = match token.as_str() {
            "todo" => "TODO",
            "fixme" => "FIXME",
            _ => continue,
        };
        if !markers.contains(&marker) {
            markers.push(marker);
        }
    }
    for phrase in STUB_PHRASES {
        if lowered.contains(phrase) && !markers.contains(&phrase) {
            markers.push(phrase);
        }
    }
    markers
}

fn stub_body(analysis: &Analysis<'_>) -> Vec<Finding> {
    let mut findings = Vec::new();

    let literals = analysis
        .scan
        .comments
        .iter()
        .map(|hit| (hit.line, hit.text.as_str()))
        .chain(
            analysis
                .scan
                .strings
                .iter()
                .map(|hit| (hit.line, hit.text.as_str())),
        );
    for (line, text) in literals {
        let markers = stub_markers_in(text);
        if markers.is_empty() {
            continue;
        }
        findings.push(error_finding(
            "STUB_BODY",
            line,
            format!("stub marker(s): {}", markers.join(", ")),
        ));
    }

    if analysis.language == Language::Python {
        for extent in analysis.functions {
            let owned = analysis.owned_body_lines(extent);
            if owned.is_empty() {
                continue;
            }
            let pass_only = owned.iter().all(|&line| {
                matches!(
                    analysis
                        .scan
                        .masked_lines
                        .get(line - 1)
                        .map(String::as_str)
                        .unwrap_or("")
                        .trim(),
                    "pass" | "..."
                )
            });
            if pass_only {
                findings.push(error_finding(
                    "STUB_BODY",
                    extent.header_line,
                    format!(
                        "function '{}' declares only a stub body ('pass')",
                        extent.name
                    ),
                ));
            }
        }
    }

    findings
}

// ------------------------------------------------------------ EMPTY_FUNCTION

fn empty_function(analysis: &Analysis<'_>) -> Vec<Finding> {
    analysis
        .functions
        .iter()
        .filter_map(|extent| {
            let is_empty = match &extent.kind {
                ExtentKind::Braced {
                    open_index,
                    close_index,
                } => analysis
                    .masked_text
                    .get(open_index + 1..*close_index)
                    .is_none_or(|inner| inner.trim().is_empty()),
                ExtentKind::Indented => !analysis.owned_body_lines(extent).iter().any(|&line| {
                    analysis
                        .scan
                        .masked_lines
                        .get(line - 1)
                        .is_some_and(|text| !text.trim().is_empty())
                }),
            };
            is_empty.then(|| {
                error_finding(
                    "EMPTY_FUNCTION",
                    extent.header_line,
                    format!("function '{}' has an empty body", extent.name),
                )
            })
        })
        .collect()
}

// ------------------------------------------------------------- GENERIC_CATCH

fn generic_catch(analysis: &Analysis<'_>) -> Vec<Finding> {
    match analysis.language {
        Language::TypeScript => ts_generic_catches(analysis),
        Language::Go => go_generic_recovers(analysis),
        Language::Python => python_generic_catches(analysis),
    }
}

fn ts_generic_catches(analysis: &Analysis<'_>) -> Vec<Finding> {
    let bytes = analysis.masked_text.as_bytes();
    let mut findings = Vec::new();
    let mut from = 0usize;
    while let Some(pos) = find_word(bytes, b"catch", from) {
        from = pos + 5;
        let mut cursor = skip_ws(bytes, pos + 5);
        if bytes.get(cursor) == Some(&b'(') {
            match matching_paren(bytes, cursor) {
                Some(after_binding) => cursor = skip_ws(bytes, after_binding),
                None => continue,
            }
        }
        if bytes.get(cursor) != Some(&b'{') {
            continue;
        }
        let Some(close) = matching_brace(bytes, cursor) else {
            continue;
        };
        let body = &analysis.masked_text[cursor + 1..close];
        if generic_ts_catch_body(body) {
            findings.push(warning_finding(
                "GENERIC_CATCH",
                analysis.index.line_of(pos),
                "catch block only logs or rethrows",
            ));
        }
    }
    findings
}

/// A catch body is generic when nothing survives removing `console.*(...)`
/// calls and `throw` statements — i.e. it was empty, log-only or rethrow-only.
fn generic_ts_catch_body(body: &str) -> bool {
    let stripped = strip_throw_statements(&strip_console_calls(body));
    stripped
        .bytes()
        .all(|byte| byte.is_ascii_whitespace() || byte == b';')
}

fn strip_console_calls(source: &str) -> String {
    let mut buffer: Vec<u8> = source.as_bytes().to_vec();
    let mut from = 0usize;
    while let Some(pos) = find_word(&buffer, b"console", from) {
        from = pos + 7;
        let mut cursor = skip_ws(&buffer, pos + 7);
        if buffer.get(cursor) != Some(&b'.') {
            continue;
        }
        cursor += 1;
        let member_len = byte_word_len(&buffer, cursor);
        if member_len == 0 {
            continue;
        }
        let open = skip_ws(&buffer, cursor + member_len);
        if buffer.get(open) != Some(&b'(') {
            continue;
        }
        let Some(close_excl) = matching_paren(&buffer, open) else {
            continue;
        };
        for slot in &mut buffer[pos..close_excl] {
            *slot = b' ';
        }
        from = close_excl;
    }
    String::from_utf8_lossy(&buffer).into_owned()
}

fn strip_throw_statements(source: &str) -> String {
    let mut buffer: Vec<u8> = source.as_bytes().to_vec();
    let len = buffer.len();
    let mut from = 0usize;
    while let Some(pos) = find_word(&buffer, b"throw", from) {
        from = pos + 5;
        let mut depth = 0usize;
        let mut end = len;
        let mut k = pos;
        while k < len {
            match buffer[k] {
                b'(' | b'[' | b'{' => depth += 1,
                b')' | b']' | b'}' => {
                    if depth == 0 {
                        end = k;
                        break;
                    }
                    depth -= 1;
                }
                b';' if depth == 0 => {
                    end = k + 1;
                    break;
                }
                _ => {}
            }
            k += 1;
        }
        for slot in &mut buffer[pos..end] {
            *slot = b' ';
        }
    }
    String::from_utf8_lossy(&buffer).into_owned()
}

fn python_generic_catches(analysis: &Analysis<'_>) -> Vec<Finding> {
    let masked = &analysis.scan.masked_lines;
    let mut findings = Vec::new();
    for i in 0..masked.len() {
        let trimmed = masked[i].trim_start();
        if !(trimmed.starts_with("except") && trimmed.ends_with(':')) {
            continue;
        }
        let indent = indent_width(&masked[i]);
        let mut body: Vec<&str> = Vec::new();
        for line in &masked[i + 1..] {
            if line.trim().is_empty() {
                continue;
            }
            if indent_width(line) > indent {
                body.push(line.trim());
            } else {
                break;
            }
        }
        let pass_only = body.is_empty()
            || body
                .iter()
                .all(|&statement| statement == "pass" || statement == "...");
        let rethrow_only =
            !body.is_empty() && body.iter().all(|statement| statement.starts_with("raise"));
        if pass_only || rethrow_only {
            findings.push(warning_finding(
                "GENERIC_CATCH",
                i + 1,
                "except clause swallows everything (pass/rethrow only)",
            ));
        }
    }
    findings
}

fn go_generic_recovers(analysis: &Analysis<'_>) -> Vec<Finding> {
    let bytes = analysis.masked_text.as_bytes();
    let mut findings = Vec::new();
    let mut from = 0usize;
    while let Some(pos) = find_word(bytes, b"recover", from) {
        from = pos + 7;
        let open = skip_ws(bytes, pos + 7);
        if bytes.get(open) != Some(&b'(') {
            continue;
        }
        let Some(close_excl) = matching_paren(bytes, open) else {
            continue;
        };

        let stmt_start = statement_start(bytes, pos);
        let normalized = collapse_statement(&analysis.masked_text[stmt_start..close_excl]);
        if matches!(normalized.as_str(), "recover()" | "_ = recover()") {
            findings.push(warning_finding(
                "GENERIC_CATCH",
                analysis.index.line_of(stmt_start),
                "recovered panic discarded silently",
            ));
            continue;
        }

        let mut k = close_excl;
        while k < bytes.len() && bytes[k] != b'\n' {
            if bytes[k] == b'{' {
                if let Some(block_close) = matching_brace(bytes, k) {
                    if analysis.masked_text[k + 1..block_close].trim().is_empty() {
                        findings.push(warning_finding(
                            "GENERIC_CATCH",
                            analysis.index.line_of(k),
                            "recovered panic swallowed by empty handler",
                        ));
                    }
                }
                break;
            }
            k += 1;
        }
    }
    findings
}

fn statement_start(bytes: &[u8], pos: usize) -> usize {
    let mut k = pos;
    while k > 0 {
        k -= 1;
        if matches!(bytes[k], b';' | b'{' | b'}' | b'\n') {
            return k + 1;
        }
    }
    0
}

fn collapse_statement(raw: &str) -> String {
    let trimmed = raw.trim().trim_end_matches(';').trim();
    let mut collapsed = String::with_capacity(trimmed.len());
    let mut pending_space = false;
    for ch in trimmed.chars() {
        if ch.is_whitespace() {
            pending_space = !collapsed.is_empty();
        } else {
            if pending_space {
                collapsed.push(' ');
                pending_space = false;
            }
            collapsed.push(ch);
        }
    }
    collapsed
}

fn byte_word_len(bytes: &[u8], at: usize) -> usize {
    bytes[at.min(bytes.len())..]
        .iter()
        .take_while(|&&byte| byte.is_ascii_alphanumeric() || byte == b'_' || byte >= 0x80)
        .count()
}

// -------------------------------------------------------------- GENERIC_NAME

fn is_generic_identifier(token: &str) -> bool {
    GENERIC_NAMES.contains(&token)
        || (token.len() > 3
            && token.starts_with("var")
            && token[3..].bytes().all(|byte| byte.is_ascii_digit()))
}

fn generic_name(analysis: &Analysis<'_>) -> Vec<Finding> {
    let mut findings = Vec::new();
    for extent in analysis.functions {
        let mut reported: HashSet<String> = HashSet::new();
        for line_no in analysis.owned_body_lines(extent) {
            let Some(line) = analysis.scan.masked_lines.get(line_no - 1) else {
                continue;
            };
            let chars: Vec<char> = line.chars().collect();
            let mut idx = 0usize;
            let mut previous_meaningful = ' ';
            while idx < chars.len() {
                let ch = chars[idx];
                if ch.is_whitespace() {
                    idx += 1;
                    continue;
                }
                if ch.is_alphanumeric() || ch == '_' || ch == '$' {
                    let start = idx;
                    while idx < chars.len()
                        && (chars[idx].is_alphanumeric() || chars[idx] == '_' || chars[idx] == '$')
                    {
                        idx += 1;
                    }
                    let ident: String = chars[start..idx].iter().collect();
                    if previous_meaningful != '.'
                        && reported.insert(ident.clone())
                        && is_generic_identifier(&ident.to_lowercase())
                    {
                        findings.push(warning_finding(
                            "GENERIC_NAME",
                            line_no,
                            format!("generic identifier '{ident}' in function '{}'", extent.name),
                        ));
                    }
                    previous_meaningful = chars[idx - 1];
                    continue;
                }
                previous_meaningful = ch;
                idx += 1;
            }
        }
    }
    findings
}

// --------------------------------------------------------- REDUNDANT_COMMENT

fn is_stopword(word: &str) -> bool {
    matches!(
        word,
        "a" | "an"
            | "the"
            | "this"
            | "that"
            | "these"
            | "those"
            | "to"
            | "for"
            | "and"
            | "or"
            | "of"
            | "in"
            | "into"
            | "on"
            | "with"
            | "by"
            | "is"
            | "are"
            | "be"
            | "been"
            | "was"
            | "were"
            | "it"
            | "its"
            | "as"
            | "at"
            | "from"
            | "new"
            | "set"
            | "get"
            | "use"
            | "used"
            | "using"
            | "should"
            | "must"
            | "can"
            | "may"
            | "will"
            | "would"
            | "then"
            | "so"
            | "here"
            | "we"
            | "you"
            | "i"
            | "your"
            | "our"
            | "all"
            | "any"
            | "some"
            | "every"
            | "via"
            | "per"
            | "each"
            | "when"
            | "while"
            | "if"
            | "else"
            | "not"
            | "no"
            | "yes"
            | "do"
            | "does"
            | "did"
            | "done"
            | "my"
            | "me"
            | "up"
            | "out"
    )
}

fn redundant_comment(analysis: &Analysis<'_>) -> Vec<Finding> {
    let mut findings = Vec::new();
    let total_lines = analysis.lines.len();
    for comment in analysis
        .scan
        .comments
        .iter()
        .filter(|hit| hit.kind == CommentKind::Line)
    {
        let comment_words: BTreeSet<String> = word_tokens(&comment.text)
            .into_iter()
            .filter(|word| !is_stopword(word))
            .collect();
        if comment_words.is_empty() {
            continue;
        }
        let next_code = ((comment.line + 1)..=total_lines).find(|&line| {
            analysis
                .scan
                .masked_lines
                .get(line - 1)
                .is_some_and(|text| !text.trim().is_empty())
        });
        let Some(next_line) = next_code else {
            continue;
        };
        let Some(code_text) = analysis.scan.masked_lines.get(next_line - 1) else {
            continue;
        };
        let line_words: BTreeSet<String> = word_tokens(code_text).into_iter().collect();
        if comment_words.is_subset(&line_words) {
            findings.push(warning_finding(
                "REDUNDANT_COMMENT",
                comment.line,
                "comment restates the following statement",
            ));
        }
    }
    findings
}

// -------------------------------------------------------------- AI_WATERMARK

fn ai_watermark(analysis: &Analysis<'_>) -> Vec<Finding> {
    let mut findings = Vec::new();
    for (idx, line) in analysis.lines.iter().enumerate() {
        let lowered = line.to_lowercase();
        let hits: Vec<&str> = WATERMARKS
            .iter()
            .copied()
            .filter(|marker| lowered.contains(marker))
            .collect();
        if !hits.is_empty() {
            findings.push(error_finding(
                "AI_WATERMARK",
                idx + 1,
                format!("AI watermark detected: {}", hits.join(", ")),
            ));
        }
    }
    findings
}

// ------------------------------------------------------------- LONG_FUNCTION

fn long_function(analysis: &Analysis<'_>) -> Vec<Finding> {
    let mut findings = Vec::new();
    for extent in analysis.functions {
        let points = match &extent.kind {
            ExtentKind::Braced { .. } => analysis
                .braced_inner(extent)
                .map_or(0, |inner| decision_points(inner, analysis.language)),
            ExtentKind::Indented => {
                let joined = analysis
                    .owned_body_lines(extent)
                    .into_iter()
                    .filter_map(|line| analysis.scan.masked_lines.get(line - 1))
                    .cloned()
                    .collect::<Vec<_>>()
                    .join("\n");
                decision_points(&joined, analysis.language)
            }
        };
        if points > DECISION_LIMIT {
            findings.push(warning_finding(
                "LONG_FUNCTION",
                extent.header_line,
                format!(
                    "function '{}' has {points} decision points (limit: {DECISION_LIMIT})",
                    extent.name
                ),
            ));
        }
    }
    findings
}

/// Counts `if`/`else`/`for`/`while`/`case` (`elif` for Python) plus `&&`/`||`.
/// Keyword matching runs on raw identifier runs — never camel-split tokens —
/// so `forEach` or `testCases` cannot masquerade as keywords.
fn decision_points(text: &str, language: Language) -> usize {
    let bytes = text.as_bytes();
    let mut operators = 0usize;
    let mut i = 0usize;
    while i + 1 < bytes.len() {
        if (bytes[i] == b'&' && bytes[i + 1] == b'&') || (bytes[i] == b'|' && bytes[i + 1] == b'|')
        {
            operators += 1;
            i += 2;
        } else {
            i += 1;
        }
    }

    let mut keywords = 0usize;
    let mut current = String::new();
    for ch in text.chars().chain(std::iter::once(' ')) {
        if ch.is_alphanumeric() || ch == '_' {
            current.push(ch);
        } else {
            match current.as_str() {
                "if" | "else" | "for" | "while" | "case" => keywords += 1,
                "elif" if language == Language::Python => keywords += 1,
                _ => {}
            }
            current.clear();
        }
    }
    keywords + operators
}

// ------------------------------------------------------------ tokenization

/// Splits an identifier into lowercase words along snake_case/camelCase seams.
pub(crate) fn split_identifier(ident: &str) -> Vec<String> {
    let mut segments: Vec<String> = Vec::new();
    let mut current = String::new();
    let mut previous_upper = false;
    for ch in ident.chars() {
        if ch == '_' || ch == '-' || ch == '$' {
            if !current.is_empty() {
                segments.push(current.to_lowercase());
                current = String::new();
            }
            previous_upper = false;
        } else if ch.is_ascii_uppercase() {
            if !current.is_empty() && !previous_upper {
                segments.push(current.to_lowercase());
                current = String::new();
            }
            current.push(ch.to_ascii_lowercase());
            previous_upper = true;
        } else {
            current.push(ch);
            previous_upper = false;
        }
    }
    if !current.is_empty() {
        segments.push(current.to_lowercase());
    }
    segments.retain(|segment| !segment.is_empty());
    segments
}

/// Lowercased word tokens of arbitrary text, with identifiers split further.
pub(crate) fn word_tokens(text: &str) -> Vec<String> {
    let mut tokens = Vec::new();
    let mut current = String::new();
    for ch in text.chars() {
        if ch.is_alphanumeric() || ch == '_' || ch == '$' {
            current.push(ch);
        } else if !current.is_empty() {
            tokens.extend(split_identifier(&current));
            current.clear();
        }
    }
    if !current.is_empty() {
        tokens.extend(split_identifier(&current));
    }
    tokens
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::functions::extract_functions;
    use crate::mask::scan;

    fn analyze(language: Language, source: &str) -> Vec<Finding> {
        let scan = scan(language, source);
        let functions = extract_functions(language, &scan);
        let lines: Vec<String> = source.lines().map(str::to_string).collect();
        let masked_text = scan.masked_lines.join("\n");
        let index = LineIndex::new(&masked_text);
        let analysis = Analysis {
            language,
            lines: &lines,
            masked_text: &masked_text,
            index: &index,
            scan: &scan,
            functions: &functions,
        };
        run_rules(&analysis)
    }

    fn rule_hits(findings: Vec<Finding>, rule: &str) -> Vec<Finding> {
        findings
            .into_iter()
            .filter(|finding| finding.rule == rule)
            .collect()
    }

    // STUB_BODY -------------------------------------------------------------

    #[test]
    fn stub_todo_comment_flags_exact_line() {
        let source = "function ok() {\n  return 1; // TODO make faster\n}\n";
        let hits = rule_hits(analyze(Language::TypeScript, source), "STUB_BODY");
        assert_eq!(hits.len(), 1);
        assert_eq!(hits[0].line, 2);
        assert!(hits[0].message.contains("TODO"));
        assert_eq!(hits[0].severity, Severity::Error);
    }

    #[test]
    fn stub_python_pass_only_body_is_stub() {
        let source = "def save():\n    pass\n\ndef real():\n    return 1\n";
        let hits = rule_hits(analyze(Language::Python, source), "STUB_BODY");
        assert_eq!(hits.len(), 1);
        assert_eq!(hits[0].line, 1);
        assert!(hits[0].message.contains("'save'"));
    }

    #[test]
    fn stub_phrase_inside_string_literal_flags() {
        let source = "def boom():\n    raise RuntimeError('not implemented yet')\n";
        let hits = rule_hits(analyze(Language::Python, source), "STUB_BODY");
        assert_eq!(hits.len(), 1);
        assert_eq!(hits[0].line, 2);
    }

    #[test]
    fn stub_fixme_word_boundary_respected() {
        let source = "func f() {\n\treturn fixmedata\n}\n";
        assert!(rule_hits(analyze(Language::Go, source), "STUB_BODY").is_empty());
    }

    // EMPTY_FUNCTION --------------------------------------------------------

    #[test]
    fn empty_functions_detected_across_languages() {
        let ts = "function hollow() {}\nconst filled = () => { return 1; };\n";
        let ts_hits = rule_hits(analyze(Language::TypeScript, ts), "EMPTY_FUNCTION");
        assert_eq!(ts_hits.len(), 1);
        assert_eq!(ts_hits[0].line, 1);

        let go = "func Hollow() {\n}\nfunc Filled() int {\n\treturn 1\n}\n";
        let go_hits = rule_hits(analyze(Language::Go, go), "EMPTY_FUNCTION");
        assert_eq!(go_hits.len(), 1);
        assert_eq!(go_hits[0].line, 1);
    }

    #[test]
    fn python_docstring_only_body_is_empty() {
        let source = "def documented():\n    \"\"\"Does nothing real.\"\"\"\n\ndef working():\n    compute()\n";
        let hits = rule_hits(analyze(Language::Python, source), "EMPTY_FUNCTION");
        assert_eq!(hits.len(), 1);
        assert_eq!(hits[0].line, 1);
    }

    #[test]
    fn pass_only_body_does_not_double_report_as_empty() {
        let findings = analyze(Language::Python, "def save():\n    pass\n");
        assert!(!findings
            .iter()
            .any(|finding| finding.rule == "EMPTY_FUNCTION"));
        assert_eq!(
            findings
                .iter()
                .filter(|finding| finding.rule == "STUB_BODY")
                .count(),
            1
        );
    }

    // GENERIC_CATCH ---------------------------------------------------------

    #[test]
    fn ts_bare_and_console_only_catches_are_generic() {
        let source = "try {\n  load();\n} catch (e) {\n  console.log(e);\n}\n\ntry {\n  save();\n} catch {\n}\n";
        let hits = rule_hits(analyze(Language::TypeScript, source), "GENERIC_CATCH");
        assert_eq!(hits.len(), 2);
        assert_eq!(hits[0].line, 3);
        assert_eq!(hits[1].line, 9);
        assert_eq!(hits[0].severity, Severity::Warning);
    }

    #[test]
    fn ts_substantive_handler_is_not_generic() {
        let source =
            "try {\n  sync();\n} catch (err) {\n  report(err);\n  throw new SyncError(err);\n}\n";
        assert!(rule_hits(analyze(Language::TypeScript, source), "GENERIC_CATCH").is_empty());
    }

    #[test]
    fn python_pass_and_rethrow_only_excepts_are_generic() {
        let source = "try:\n    load()\nexcept Exception:\n    pass\n\ntry:\n    parse()\nexcept ValueError:\n    raise\n";
        let hits = rule_hits(analyze(Language::Python, source), "GENERIC_CATCH");
        assert_eq!(hits.len(), 2);
        assert_eq!(hits[0].line, 3);
        assert_eq!(hits[1].line, 8);
    }

    #[test]
    fn go_silenced_and_empty_recoveries_are_generic() {
        let source = "func run() {\n\t_ = recover()\n}\n\nfunc guarded() {\n\tdefer func() {\n\t\tif r := recover(); r != nil {\n\t\t}\n\t}()\n}\n";
        let hits = rule_hits(analyze(Language::Go, source), "GENERIC_CATCH");
        assert_eq!(hits.len(), 2);
        assert!(hits.iter().any(|hit| hit.line == 2));
        assert!(hits.iter().any(|hit| hit.line == 7));
    }

    #[test]
    fn go_substantive_recovery_is_not_generic() {
        let source = "func guarded() {\n\tdefer func() {\n\t\tif r := recover(); r != nil {\n\t\t\tlog.Println(\"recovered:\", r)\n\t\t}\n\t}()\n}\n";
        assert!(rule_hits(analyze(Language::Go, source), "GENERIC_CATCH").is_empty());
    }

    // GENERIC_NAME ----------------------------------------------------------

    #[test]
    fn generic_names_inside_functions_are_flagged_once_each() {
        let source = "const data = loadTopLevel();\n\nfunction process(data, bar) {\n  const temp = transform(data);\n  return { value: temp, tag: bar };\n}\n";
        let hits = rule_hits(analyze(Language::TypeScript, source), "GENERIC_NAME");
        assert_eq!(hits.len(), 3);
        assert!(!hits.iter().any(|hit| hit.line == 1));
    }

    #[test]
    fn member_access_and_var_n_patterns() {
        let source = "def handle(self):\n    return self.data\n\ndef other(payload):\n    temp = transform(payload)\n    var1 = temp\n    return var1\n";
        let hits = rule_hits(analyze(Language::Python, source), "GENERIC_NAME");
        assert_eq!(hits.len(), 2);
        assert!(hits.iter().any(|hit| hit.message.contains("'temp'")));
        assert!(hits.iter().any(|hit| hit.message.contains("'var1'")));
    }

    // REDUNDANT_COMMENT -----------------------------------------------------

    #[test]
    fn restating_comment_is_flagged() {
        let source = "// create user\nconst user = createUser(payload);\n";
        let hits = rule_hits(analyze(Language::TypeScript, source), "REDUNDANT_COMMENT");
        assert_eq!(hits.len(), 1);
        assert_eq!(hits[0].line, 1);
    }

    #[test]
    fn informative_comment_survives() {
        let source = "// retry after backoff; upstream rate-limits bursts\nconst session = retryWithBackoff(client);\n";
        let hits = rule_hits(analyze(Language::TypeScript, source), "REDUNDANT_COMMENT");
        assert!(hits.is_empty());
    }

    #[test]
    fn block_comments_are_exempt_from_redundancy() {
        let source = "/* user */\nclass User {}\n";
        assert!(rule_hits(analyze(Language::TypeScript, source), "REDUNDANT_COMMENT").is_empty());
    }

    // AI_WATERMARK ----------------------------------------------------------

    #[test]
    fn all_watermark_variants_flag_their_own_lines() {
        let source = "// Generated by CodeGen v2\nconst x = 1;\n// As an AI assistant, here is...\n// co-authored-by: AI <bot@example.com>\n";
        let hits = rule_hits(analyze(Language::TypeScript, source), "AI_WATERMARK");
        assert_eq!(hits.len(), 3);
        assert_eq!(hits[0].line, 1);
        assert_eq!(hits[1].line, 3);
        assert_eq!(hits[2].line, 4);
        assert_eq!(hits[0].severity, Severity::Error);
    }

    #[test]
    fn human_attribution_is_not_a_watermark() {
        let source = "// co-authored-by: Alice <alice@example.com>\nconst y = 2;\n";
        assert!(rule_hits(analyze(Language::TypeScript, source), "AI_WATERMARK").is_empty());
    }

    // LONG_FUNCTION ---------------------------------------------------------

    fn ladder(count: usize) -> String {
        let mut body = String::from("function decisionSoup(input) {\n  let acc = 0;\n");
        for k in 0..count {
            body.push_str(&format!(
                "  if (input.a{k} && input.b{k}) {{\n    acc += {k};\n  }}\n"
            ));
        }
        body.push_str("  return acc;\n}\n");
        body
    }

    #[test]
    fn long_function_flags_above_limit() {
        let source = ladder(8);
        let hits = rule_hits(analyze(Language::TypeScript, &source), "LONG_FUNCTION");
        assert_eq!(hits.len(), 1);
        assert_eq!(hits[0].line, 1);
        assert!(hits[0].message.contains("16 decision points"));
    }

    #[test]
    fn function_at_exact_limit_is_fine() {
        let source = ladder(7);
        assert!(rule_hits(analyze(Language::TypeScript, &source), "LONG_FUNCTION").is_empty());
    }

    #[test]
    fn python_elif_counts_towards_decisions() {
        let mut source = String::from("def route(kind):\n");
        for k in 0..9 {
            source.push_str(&format!("    if kind == {k}:\n        return {k}\n"));
        }
        source.push_str("    return -1\n");
        assert!(rule_hits(analyze(Language::Python, &source), "LONG_FUNCTION").is_empty());

        let mut dense = String::from("def dense(kind):\n");
        for k in 0..9 {
            dense.push_str(&format!("    if kind == {k}:\n        return {k}\n    elif kind == -{k}:\n        return -{k}\n"));
        }
        let hits = rule_hits(analyze(Language::Python, &dense), "LONG_FUNCTION");
        assert_eq!(hits.len(), 1);
    }

    #[test]
    fn keyword_lookalikes_do_not_count() {
        let source = "function f(items) {\n  items.forEach(item => item.testCases.length);\n  return items.length;\n}\n";
        assert!(rule_hits(analyze(Language::TypeScript, source), "LONG_FUNCTION").is_empty());
    }

    // normalization ---------------------------------------------------------

    #[test]
    fn findings_are_ordered_by_line_then_rule_order() {
        let source = "// TODO cleanup\nfunction broken(data) {}\n";
        let findings = analyze(Language::TypeScript, source);
        assert!(findings.windows(2).all(|pair| pair[0].line <= pair[1].line));
        let first_line_rules: Vec<&str> = findings
            .iter()
            .filter(|finding| finding.line == 2)
            .map(|finding| finding.rule.as_str())
            .collect();
        assert_eq!(first_line_rules, vec!["EMPTY_FUNCTION", "GENERIC_NAME"]);
    }
}
